// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetserver.NewFolder;

#nullable disable

namespace aspnetserver.NewFolder.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220111020615_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("aspnetserver.NewFolder.Plant", b =>
                {
                    b.Property<int>("plantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("WateringStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("lastWatered")
                        .HasColumnType("TEXT");

                    b.HasKey("plantId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            plantId = 1,
                            Content = "This is plant 1 and it has some very interesting traits.",
                            Name = "Rose",
                            WateringStatus = false,
                            lastWatered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            plantId = 2,
                            Content = "This is plant 2 and it has some very interesting traits.",
                            Name = "Habiscus",
                            WateringStatus = false,
                            lastWatered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            plantId = 3,
                            Content = "This is plant 3 and it has some very interesting traits.",
                            Name = "Jasmine",
                            WateringStatus = false,
                            lastWatered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            plantId = 4,
                            Content = "This is plant 4 and it has some very interesting traits.",
                            Name = "Sunflower",
                            WateringStatus = false,
                            lastWatered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            plantId = 5,
                            Content = "This is plant 5 and it has some very interesting traits.",
                            Name = "Yellow Tulip",
                            WateringStatus = false,
                            lastWatered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
